import type { Employee } from "../interfaces/Employee"

export const mockEmployees: Employee[] = [
  {
    id: "emp-001",
    name: "Juan Pérez",
    department: "Ventas",
    position: "Gerente de Ventas",
    location: "Oficina Central",
    email: "juan.perez@empresa.com",
    phone: "+1234567890",
    maxOvertimeHours: 10,
  },
  {
    id: "emp-002",
    name: "María Rodríguez",
    department: "Recursos Humanos",
    position: "Especialista de RRHH",
    location: "Oficina Central",
    email: "maria.rodriguez@empresa.com",
    phone: "+1234567891",
    maxOvertimeHours: 8,
  },
  {
    id: "emp-003",
    name: "Carlos Gómez",
    department: "TI",
    position: "Desarrollador Senior",
    location: "Remoto",
    email: "carlos.gomez@empresa.com",
    phone: "+1234567892",
    maxOvertimeHours: 12,
  },
  {
    id: "emp-004",
    name: "Ana Martínez",
    department: "Marketing",
    position: "Coordinadora de Marketing",
    location: "Oficina Central",
    email: "ana.martinez@empresa.com",
    phone: "+1234567893",
    maxOvertimeHours: 8,
  },
  {
    id: "emp-005",
    name: "Luis Sánchez",
    department: "Ventas",
    position: "Representante de Ventas",
    location: "Sucursal Norte",
    email: "luis.sanchez@empresa.com",
    phone: "+1234567894",
    maxOvertimeHours: 10,
  },
  {
    id: "emp-006",
    name: "Laura Torres",
    department: "Finanzas",
    position: "Contadora",
    location: "Oficina Central",
    email: "laura.torres@empresa.com",
    phone: "+1234567895",
    maxOvertimeHours: 6,
  },
  {
    id: "emp-007",
    name: "Pedro Ramírez",
    department: "Operaciones",
    position: "Supervisor",
    location: "Planta de Producción",
    email: "pedro.ramirez@empresa.com",
    phone: "+1234567896",
    maxOvertimeHours: 15,
  },
  {
    id: "emp-008",
    name: "Sofía Vargas",
    department: "Atención al Cliente",
    position: "Representante de Servicio",
    location: "Centro de Llamadas",
    email: "sofia.vargas@empresa.com",
    phone: "+1234567897",
    maxOvertimeHours: 8,
  },
]
