import type { Employee } from "../interfaces/Employee";

export const mockEmployees: Employee[] = [
  {
    id: "emp-001",
    name: "Juan Pérez",
    department: "Ventas",
    position: "Gerente de Ventas",
    location: "Oficina Central",
    email: "juan.perez@empresa.com",
    phone: "+1234567890",
    maxOvertimeHours: 10,
  },
  {
    id: "emp-002",
    name: "María Rodríguez",
    department: "Recursos Humanos",
    position: "Especialista de RRHH",
    location: "Oficina Central",
    email: "maria.rodriguez@empresa.com",
    phone: "+1234567891",
    maxOvertimeHours: 8,
  },
  {
    id: "emp-003",
    name: "Carlos Gómez",
    department: "TI",
    position: "Desarrollador Senior",
    location: "Remoto",
    email: "carlos.gomez@empresa.com",
    phone: "+1234567892",
    maxOvertimeHours: 12,
  },
  {
    id: "emp-004",
    name: "Ana Martínez",
    department: "Marketing",
    position: "Coordinadora de Marketing",
    location: "Oficina Central",
    email: "ana.martinez@empresa.com",
    phone: "+1234567893",
    maxOvertimeHours: 8,
  },
  {
    id: "emp-005",
    name: "Luis Sánchez",
    department: "Ventas",
    position: "Representante de Ventas",
    location: "Sucursal Norte",
    email: "luis.sanchez@empresa.com",
    phone: "+1234567894",
    maxOvertimeHours: 10,
  },
  {
    id: "emp-006",
    name: "Laura Torres",
    department: "Finanzas",
    position: "Contadora",
    location: "Oficina Central",
    email: "laura.torres@empresa.com",
    phone: "+1234567895",
    maxOvertimeHours: 6,
  },
  {
    id: "emp-007",
    name: "Pedro Ramírez",
    department: "Operaciones",
    position: "Supervisor",
    location: "Planta de Producción",
    email: "pedro.ramirez@empresa.com",
    phone: "+1234567896",
    maxOvertimeHours: 15,
  },
  {
    id: "emp-008",
    name: "Sofía Vargas",
    department: "Atención al Cliente",
    position: "Representante de Servicio",
    location: "Centro de Llamadas",
    email: "sofia.vargas@empresa.com",
    phone: "+1234567897",
    maxOvertimeHours: 8,
  },
  {
    id: "emp-010",
    name: "Elena Navarro",
    department: "Marketing",
    position: "Diseñadora Gráfica",
    location: "Oficina Central",
    email: "elena.navarro@empresa.com",
    phone: "+1234567899",
    maxOvertimeHours: 10,
  },
  {
    id: "emp-011",
    name: "Miguel Ángel Castro",
    department: "Ventas",
    position: "Ejecutivo de Cuentas",
    location: "Sucursal Sur",
    email: "miguel.castro@empresa.com",
    phone: "+1234567800",
    maxOvertimeHours: 15,
  },
  {
    id: "emp-012",
    name: "Carmen Ortega",
    department: "Recursos Humanos",
    position: "Reclutadora",
    location: "Oficina Central",
    email: "carmen.ortega@empresa.com",
    phone: "+1234567801",
    maxOvertimeHours: 5,
  },
  {
    id: "emp-013",
    name: "Javier López",
    department: "Finanzas",
    position: "Analista Financiero",
    location: "Oficina Central",
    email: "javier.lopez@empresa.com",
    phone: "+1234567802",
    maxOvertimeHours: 10,
  },
  {
    id: "emp-014",
    name: "Patricia Morales",
    department: "TI",
    position: "QA Tester",
    location: "Remoto",
    email: "patricia.morales@empresa.com",
    phone: "+1234567803",
    maxOvertimeHours: 15,
  },
  {
    id: "emp-015",
    name: "Fernando Díaz",
    department: "Operaciones",
    position: "Jefe de Almacén",
    location: "Centro de Distribución",
    email: "fernando.diaz@empresa.com",
    phone: "+1234567804",
    maxOvertimeHours: 20,
  },
  {
    id: "emp-016",
    name: "Lucía Herrera",
    department: "Atención al Cliente",
    position: "Supervisora de Call Center",
    location: "Centro de Llamadas",
    email: "lucia.herrera@empresa.com",
    phone: "+1234567805",
    maxOvertimeHours: 12,
  },
  {
    id: "emp-017",
    name: "Daniel Flores",
    department: "Marketing",
    position: "Especialista en SEO",
    location: "Oficina Central",
    email: "daniel.flores@empresa.com",
    phone: "+1234567806",
    maxOvertimeHours: 8,
  },
  {
    id: "emp-018",
    name: "Mónica Jiménez",
    department: "Ventas",
    position: "Gerente Regional",
    location: "Sucursal Este",
    email: "monica.jimenez@empresa.com",
    phone: "+1234567807",
    maxOvertimeHours: 15,
  },
  {
    id: "emp-019",
    name: "Gabriel Reyes",
    department: "TI",
    position: "Desarrollador Frontend",
    location: "Oficina Central",
    email: "gabriel.reyes@empresa.com",
    phone: "+1234567808",
    maxOvertimeHours: 12,
  },
  {
    id: "emp-020",
    name: "Isabel Muñoz",
    department: "Finanzas",
    position: "Tesorera",
    location: "Oficina Central",
    email: "isabel.munoz@empresa.com",
    phone: "+1234567809",
    maxOvertimeHours: 5,
  },
  {
    id: "emp-021",
    name: "Raúl Delgado",
    department: "Recursos Humanos",
    position: "Gestor de Nómina",
    location: "Oficina Central",
    email: "raul.delgado@empresa.com",
    phone: "+1234567810",
    maxOvertimeHours: 8,
  },
  {
    id: "emp-022",
    name: "Diana Vega",
    department: "Operaciones",
    position: "Analista de Procesos",
    location: "Planta de Producción",
    email: "diana.vega@empresa.com",
    phone: "+1234567811",
    maxOvertimeHours: 10,
  },
  {
    id: "emp-023",
    name: "Alejandro Campos",
    department: "TI",
    position: "Desarrollador Backend",
    location: "Remoto",
    email: "alejandro.campos@empresa.com",
    phone: "+1234567812",
    maxOvertimeHours: 15,
  },
  {
    id: "emp-024",
    name: "Beatriz Ramos",
    department: "Marketing",
    position: "Community Manager",
    location: "Oficina Central",
    email: "beatriz.ramos@empresa.com",
    phone: "+1234567813",
    maxOvertimeHours: 10,
  },
  {
    id: "emp-025",
    name: "Héctor Ruiz",
    department: "Ventas",
    position: "Asesor Comercial",
    location: "Sucursal Norte",
    email: "hector.ruiz@empresa.com",
    phone: "+1234567814",
    maxOvertimeHours: 12,
  },
];
