import { Marking } from "../interfaces/Marking";

// Sedes para usar en los marcajes
export const mockSites = [
  "Sede Principal Lima",
  "Sucursal Piura",
  "Oficina Arequipa",
  "Centro Comercial Jockey Plaza",
  "Almacén Central Callao",
  "Torre Empresarial San Isidro",
  "Campus Universitario",
  "Sucursal Trujillo",
];

// Tipos de marcaje
export const mockMarkingTypes = [
  "Turno Mañana M1",
  "Turno Tarde T1",
  "Turno Noche N1",
  "Entrada General",
  "Salida General",
  "Pausa Almuerzo",
  "Retorno Almuerzo",
];

// Ubicaciones
export const mockLocations = [
  "Sede Hotel Dep. Sucursal Piura",
  "Oficina Principal Lima",
  "Almacén Arequipa",
  "Cliente Corp. XYZ",
  "Centro Comercial Jockey Plaza",
  "Torre Empresarial San Isidro",
  "Campus Universitario",
  "Remoto",
];

// Datos mockeados para marcajes
export const mockMarkings: Marking[] = [
  {
    id: "mark-001",
    dateStr: "01/05/2025",
    time: "8",
    site: "Sede Principal Lima",
    type: "ENTRADA",
    details: "Ingreso puntual",
    location: "Oficina Principal Lima",
    markingType: "Entrada General",
    createdBy: "Sistema de marcación biométrico",
    employeeId: "emp-123",
    status: "APPROVED",
  },
  {
    id: "mark-002",
    dateStr: "01/05/2025",
    time: "23",
    site: "Sede Principal Lima",
    type: "SALIDA",
    details: "Salida con horas extras",
    location: "Oficina Principal Lima",
    markingType: "Salida General",
    createdBy: "Sistema de marcación biométrico",
    employeeId: "emp-123",
    status: "PENDING",
  },
  {
    id: "mark-003",
    dateStr: "02/05/2025",
    time: "8",
    site: "Sucursal Piura",
    type: "ENTRADA",
    details: "Ingreso puntual - Visita a sucursal",
    location: "Sede Hotel Dep. Sucursal Piura",
    markingType: "Entrada General",
    createdBy: "Aplicación móvil",
    employeeId: "emp-123",
    status: "APPROVED",
  },
  {
    id: "mark-004",
    dateStr: "02/05/2025",
    time: "15",
    site: "Sucursal Piura",
    type: "SALIDA",
    details: "Fin de visita a sucursal",
    location: "Sede Hotel Dep. Sucursal Piura",
    markingType: "Salida General",
    createdBy: "Aplicación móvil",
    employeeId: "emp-123",
    status: "APPROVED",
  },
  {
    id: "mark-005",
    dateStr: "03/05/2025",
    time: "14.983333",
    site: "Almacén Central Callao",
    type: "ENTRADA",
    details: "Ingreso para inventario especial",
    location: "Almacén Arequipa",
    markingType: "Turno Tarde T1",
    createdBy: "Sistema de marcación biométrico",
    employeeId: "emp-123",
    status: "APPROVED",
  },
  {
    id: "mark-006",
    dateStr: "03/05/2025",
    time: "12",
    site: "Almacén Central Callao",
    type: "SALIDA",
    details: "Fin de inventario especial",
    location: "Almacén Arequipa",
    markingType: "Salida General",
    createdBy: "Supervisor: Manuel Gutiérrez",
    employeeId: "emp-123",
    status: "APPROVED",
  },
  {
    id: "mark-007",
    dateStr: "28/04/2025",
    time: "8",
    site: "Oficina Arequipa",
    type: "ENTRADA",
    details: "Inicio de jornada regular",
    location: "Almacén Arequipa",
    markingType: "Turno Mañana M1",
    createdBy: "Sistema de marcación biométrico",
    employeeId: "emp-123",
    status: "APPROVED",
  },
  {
    id: "mark-008",
    dateStr: "28/04/2025",
    time: "16",
    site: "Oficina Arequipa",
    type: "SALIDA",
    details: "Fin de jornada regular",
    location: "Almacén Arequipa",
    markingType: "Salida General",
    createdBy: "Sistema de marcación biométrico",
    employeeId: "emp-123",
    status: "APPROVED",
  },
  {
    id: "mark-009",
    dateStr: "29/04/2025",
    time: "13",
    site: "Centro Comercial Jockey Plaza",
    type: "ENTRADA",
    details: "Visita a cliente para presentación de producto",
    location: "Cliente Corp. XYZ",
    markingType: "Entrada General",
    createdBy: "Aplicación móvil",
    employeeId: "emp-123",
    status: "APPROVED",
  },
  {
    id: "mark-010",
    dateStr: "29/04/2025",
    time: "22",
    site: "Centro Comercial Jockey Plaza",
    type: "SALIDA",
    details: "Fin de presentación y cierre de negocio",
    location: "Cliente Corp. XYZ",
    markingType: "Salida General",
    createdBy: "Aplicación móvil",
    employeeId: "emp-123",
    status: "APPROVED",
  },
  {
    id: "mark-011",
    dateStr: "30/04/2025",
    time: "15",
    site: "Torre Empresarial San Isidro",
    type: "ENTRADA",
    details: "Reunión con equipo directivo",
    location: "Torre Empresarial San Isidro",
    markingType: "Entrada General",
    createdBy: "Recepción del edificio",
    employeeId: "emp-123",
    status: "PENDING",
  },
];

// Simulación de la información de un empleado
export const mockEmployee = {
  id: "emp-123",
  name: "Ana María Santos",
  position: "Especialista en Marketing Digital",
  department: "Marketing",
  employeeCode: "EMP-2023-0456",
};
