import { MapPin, Clock, Fingerprint } from "lucide-react";

export interface Employee {
  id: string;
  name: string;
  department: string;
  documentNumber?: string;
  personType?: string;
  contractInfo?: string;
  site?: string;
  position?: string;
  workedHours?: string;
  ordinaryHours?: string;
  absenceHours?: string;
}

// --- MOCK EMPLOYEE DATA (Expanded to 10 employees) ---
export const mockEmployees: Employee[] = [
  // (Data from previous response - kept for brevity)
  // Existing 3
  {
    id: "emp1",
    name: "Ana María Santos",
    department: "Habitaciones",
    documentNumber: "1018MP10",
    personType: "Empleado",
    contractInfo: "Mantenimiento - 28-04-2023",
    site: "Sede Principal",
    position: "Camarera",
    workedHours: "39 hrs 30 min",
    ordinaryHours: "38 hrs 0 min",
    absenceHours: "2 hrs 30 min",
  },
  {
    id: "emp3",
    name: "Juan Pérez",
    department: "Ventas",
    documentNumber: "A87B45C1",
    personType: "Empleado",
    contractInfo: "Ventas Senior - 01-06-2021",
    site: "Oficina Central",
    position: "Gerente de Ventas",
    workedHours: "41 hrs 30 min",
    ordinaryHours: "40 hrs 0 min",
    absenceHours: "1 hrs 30 min",
  },
  // Added 7 more
  {
    id: "emp4",
    name: "Luis Gómez",
    department: "Mantenimiento",
    documentNumber: "C12D34E5",
    personType: "Empleado",
    contractInfo: "Técnico - 10-09-2022",
    site: "Sede Principal",
    position: "Técnico Electricista",
    workedHours: "40 hrs 0 min",
    ordinaryHours: "40 hrs 0 min",
    absenceHours: "0 hrs",
  },
  {
    id: "emp5",
    name: "Sofía Martínez",
    department: "Cocina",
    documentNumber: "F67G89H0",
    personType: "Empleado",
    contractInfo: "Cocinero - 05-03-2024",
    site: "Sede Principal",
    position: "Ayudante de Cocina",
    workedHours: "38 hrs 0 min",
    ordinaryHours: "38 hrs 0 min",
    absenceHours: "2 hrs", // Example absence
  },
  {
    id: "emp6",
    name: "Ricardo Díaz",
    department: "Administración",
    documentNumber: "I12J34K5",
    personType: "Empleado",
    contractInfo: "Contable - 11-11-2020",
    site: "Oficina Central",
    position: "Contable Junior",
    workedHours: "40 hrs 0 min",
    ordinaryHours: "40 hrs 0 min",
    absenceHours: "0 hrs",
  },
  {
    id: "emp7",
    name: "Elena Fernández",
    department: "Marketing",
    documentNumber: "L67M89N0",
    personType: "Empleado",
    contractInfo: "Especialista - 01-02-2023",
    site: "Oficina Central",
    position: "Especialista SEO",
    workedHours: "42 hrs 0 min", // Example OT
    ordinaryHours: "40 hrs 0 min",
    absenceHours: "0 hrs",
  },
  {
    id: "emp8",
    name: "Javier Morales",
    department: "Seguridad",
    documentNumber: "O12P34Q5",
    personType: "Empleado",
    contractInfo: "Vigilante - 30-07-2021",
    site: "Sede Principal",
    position: "Vigilante Nocturno",
    workedHours: "40 hrs 0 min",
    ordinaryHours: "40 hrs 0 min",
    absenceHours: "0 hrs",
  },
  {
    id: "emp9",
    name: "Patricia Núñez",
    department: "Recursos Humanos",
    documentNumber: "R67S89T0",
    personType: "Empleado",
    contractInfo: "Generalista - 15-05-2022",
    site: "Oficina Central",
    position: "Técnico RRHH",
    workedHours: "39 hrs 0 min",
    ordinaryHours: "40 hrs 0 min",
    absenceHours: "1 hrs", // Example absence
  },
  {
    id: "emp10",
    name: "Andrés Castro",
    department: "Dirección",
    documentNumber: "U12V34W5",
    personType: "Directivo",
    contractInfo: "Director Hotel - 01-01-2019",
    site: "Sede Principal",
    position: "Director General",
    workedHours: "45 hrs 0 min", // Example OT
    ordinaryHours: "40 hrs 0 min",
    absenceHours: "0 hrs",
  },
];

export const mockSchedules = [
  // Ana María Santos (emp1)
  {
    id: "s1",
    employeeId: "emp1",
    dayKey: "lun",
    label: "Turno M1",
    startTime: 8.0,
    endTime: 16.0,
  },
  {
    id: "s2",
    employeeId: "emp1",
    dayKey: "mar",
    label: "Turno M1",
    startTime: 8.0,
    endTime: 16.0,
  },
  {
    id: "s3",
    employeeId: "emp1",
    dayKey: "mié",
    label: "Turno M1",
    startTime: 8.0,
    endTime: 16.0,
  }, // Day with absence
  {
    id: "s4",
    employeeId: "emp1",
    dayKey: "jue",
    label: "Turno M1",
    startTime: 8.0,
    endTime: 16.0,
  }, // Day with overtime
  {
    id: "s5",
    employeeId: "emp1",
    dayKey: "vie",
    label: "Turno M1",
    startTime: 8.0,
    endTime: 16.0,
  }, // Left early
  {
    id: "s14",
    employeeId: "emp1",
    dayKey: "sáb",
    label: "Turno SAB",
    startTime: 9.0,
    endTime: 13.0,
  }, // Added Saturday Schedule
  // Carmen Rodríguez (emp2)
  {
    id: "s6",
    employeeId: "emp2",
    dayKey: "lun",
    label: "Turno T1",
    startTime: 14.0,
    endTime: 22.0,
  },
  {
    id: "s7",
    employeeId: "emp2",
    dayKey: "mar",
    label: "Turno T1",
    startTime: 14.0,
    endTime: 22.0,
  }, // Normal day
  {
    id: "s8",
    employeeId: "emp2",
    dayKey: "mié",
    label: "Turno T1",
    startTime: 14.0,
    endTime: 22.0,
  }, // Late arrival
  {
    id: "s9",
    employeeId: "emp2",
    dayKey: "jue",
    label: "Turno T1",
    startTime: 14.0,
    endTime: 22.0,
  }, // No work logged (full absence)
  {
    id: "s10",
    employeeId: "emp2",
    dayKey: "vie",
    label: "Turno T1",
    startTime: 14.0,
    endTime: 22.0,
  }, // Extra long overtime
  // Juan Pérez (emp3)
  {
    id: "s11",
    employeeId: "emp3",
    dayKey: "lun",
    label: "Turno S2",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "s12",
    employeeId: "emp3",
    dayKey: "mar",
    label: "Turno S2",
    startTime: 9.0,
    endTime: 17.0,
  }, // Overtime
  {
    id: "s13",
    employeeId: "emp3",
    dayKey: "sáb",
    label: "Turno SAB",
    startTime: 9.0,
    endTime: 13.0,
  }, // Worked Saturday shift
  {
    id: "s15",
    employeeId: "emp3",
    dayKey: "mié",
    label: "Turno S2",
    startTime: 9.0,
    endTime: 17.0,
  }, // Normal
  {
    id: "s16",
    employeeId: "emp3",
    dayKey: "jue",
    label: "Turno S2",
    startTime: 9.0,
    endTime: 17.0,
  }, // Late Start
  {
    id: "s17",
    employeeId: "emp3",
    dayKey: "vie",
    label: "Turno S2",
    startTime: 9.0,
    endTime: 17.0,
  }, // Left Early
  // Luis Gómez (emp4) - Standard 9-5 Mon-Fri
  {
    id: "s18",
    employeeId: "emp4",
    dayKey: "lun",
    label: "Oficina",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "s19",
    employeeId: "emp4",
    dayKey: "mar",
    label: "Oficina",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "s20",
    employeeId: "emp4",
    dayKey: "mié",
    label: "Oficina",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "s21",
    employeeId: "emp4",
    dayKey: "jue",
    label: "Oficina",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "s22",
    employeeId: "emp4",
    dayKey: "vie",
    label: "Oficina",
    startTime: 9.0,
    endTime: 17.0,
  },
  // Sofía Martínez (emp5) - Morning shift Tue-Sat
  {
    id: "s23",
    employeeId: "emp5",
    dayKey: "mar",
    label: "Turno Cocina M",
    startTime: 7.0,
    endTime: 15.0,
  },
  {
    id: "s24",
    employeeId: "emp5",
    dayKey: "mié",
    label: "Turno Cocina M",
    startTime: 7.0,
    endTime: 15.0,
  },
  {
    id: "s25",
    employeeId: "emp5",
    dayKey: "jue",
    label: "Turno Cocina M",
    startTime: 7.0,
    endTime: 15.0,
  }, // Example Absence Day
  {
    id: "s26",
    employeeId: "emp5",
    dayKey: "vie",
    label: "Turno Cocina M",
    startTime: 7.0,
    endTime: 15.0,
  },
  {
    id: "s27",
    employeeId: "emp5",
    dayKey: "sáb",
    label: "Turno Cocina M",
    startTime: 8.0,
    endTime: 14.0,
  },
  // Ricardo Díaz (emp6) - Standard 8-4 Mon-Fri
  {
    id: "s28",
    employeeId: "emp6",
    dayKey: "lun",
    label: "Admin",
    startTime: 8.0,
    endTime: 16.0,
  },
  {
    id: "s29",
    employeeId: "emp6",
    dayKey: "mar",
    label: "Admin",
    startTime: 8.0,
    endTime: 16.0,
  },
  {
    id: "s30",
    employeeId: "emp6",
    dayKey: "mié",
    label: "Admin",
    startTime: 8.0,
    endTime: 16.0,
  },
  {
    id: "s31",
    employeeId: "emp6",
    dayKey: "jue",
    label: "Admin",
    startTime: 8.0,
    endTime: 16.0,
  },
  {
    id: "s32",
    employeeId: "emp6",
    dayKey: "vie",
    label: "Admin",
    startTime: 8.0,
    endTime: 16.0,
  },
  // Elena Fernández (emp7) - Standard 10-6 Mon-Fri
  {
    id: "s33",
    employeeId: "emp7",
    dayKey: "lun",
    label: "Mkt",
    startTime: 10.0,
    endTime: 18.0,
  },
  {
    id: "s34",
    employeeId: "emp7",
    dayKey: "mar",
    label: "Mkt",
    startTime: 10.0,
    endTime: 18.0,
  }, // Overtime day
  {
    id: "s35",
    employeeId: "emp7",
    dayKey: "mié",
    label: "Mkt",
    startTime: 10.0,
    endTime: 18.0,
  },
  {
    id: "s36",
    employeeId: "emp7",
    dayKey: "jue",
    label: "Mkt",
    startTime: 10.0,
    endTime: 18.0,
  },
  {
    id: "s37",
    employeeId: "emp7",
    dayKey: "vie",
    label: "Mkt",
    startTime: 10.0,
    endTime: 18.0,
  },
  // Javier Morales (emp8) - Night Shift Mon-Fri
  {
    id: "s38",
    employeeId: "emp8",
    dayKey: "lun",
    label: "Noche",
    startTime: 22.0,
    endTime: 6.0,
  }, // Spans across midnight - simplified for this view
  {
    id: "s39",
    employeeId: "emp8",
    dayKey: "mar",
    label: "Noche",
    startTime: 22.0,
    endTime: 6.0,
  },
  {
    id: "s40",
    employeeId: "emp8",
    dayKey: "mié",
    label: "Noche",
    startTime: 22.0,
    endTime: 6.0,
  },
  {
    id: "s41",
    employeeId: "emp8",
    dayKey: "jue",
    label: "Noche",
    startTime: 22.0,
    endTime: 6.0,
  },
  {
    id: "s42",
    employeeId: "emp8",
    dayKey: "vie",
    label: "Noche",
    startTime: 22.0,
    endTime: 6.0,
  },
  // Patricia Núñez (emp9) - Standard 9-5 Mon-Fri
  {
    id: "s43",
    employeeId: "emp9",
    dayKey: "lun",
    label: "RRHH",
    startTime: 9.0,
    endTime: 17.0,
  }, // Absent day
  {
    id: "s44",
    employeeId: "emp9",
    dayKey: "mar",
    label: "RRHH",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "s45",
    employeeId: "emp9",
    dayKey: "mié",
    label: "RRHH",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "s46",
    employeeId: "emp9",
    dayKey: "jue",
    label: "RRHH",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "s47",
    employeeId: "emp9",
    dayKey: "vie",
    label: "RRHH",
    startTime: 9.0,
    endTime: 17.0,
  },
  // Andrés Castro (emp10) - Flexible Director hours Mon-Sat
  {
    id: "s48",
    employeeId: "emp10",
    dayKey: "lun",
    label: "Dirección",
    startTime: 8.0,
    endTime: 18.0,
  }, // Long day
  {
    id: "s49",
    employeeId: "emp10",
    dayKey: "mar",
    label: "Dirección",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "s50",
    employeeId: "emp10",
    dayKey: "mié",
    label: "Dirección",
    startTime: 9.0,
    endTime: 16.0,
  },
  {
    id: "s51",
    employeeId: "emp10",
    dayKey: "jue",
    label: "Dirección",
    startTime: 8.5,
    endTime: 17.5,
  },
  {
    id: "s52",
    employeeId: "emp10",
    dayKey: "vie",
    label: "Dirección",
    startTime: 10.0,
    endTime: 19.0,
  }, // Long day
  {
    id: "s53",
    employeeId: "emp10",
    dayKey: "sáb",
    label: "Dirección",
    startTime: 9.0,
    endTime: 13.0,
  },
];

export const mockWorkedTimes = [
  // (Data from previous response - kept for brevity)
  // Ana María Santos (emp1)
  {
    id: "w1",
    employeeId: "emp1",
    dayKey: "lun",
    startTime: 8.0,
    endTime: 16.0,
  },
  {
    id: "w2",
    employeeId: "emp1",
    dayKey: "mar",
    startTime: 7.9,
    endTime: 16.1,
  },
  {
    id: "w3",
    employeeId: "emp1",
    dayKey: "mié",
    startTime: 9.5,
    endTime: 16.0,
  },
  {
    id: "w4",
    employeeId: "emp1",
    dayKey: "jue",
    startTime: 8.0,
    endTime: 17.5,
  },
  {
    id: "w5",
    employeeId: "emp1",
    dayKey: "vie",
    startTime: 8.0,
    endTime: 15.0,
  },
  {
    id: "w14",
    employeeId: "emp1",
    dayKey: "sáb",
    startTime: 9.1,
    endTime: 12.8,
  },
  // Carmen Rodríguez (emp2)
  {
    id: "w6",
    employeeId: "emp2",
    dayKey: "lun",
    startTime: 13.9,
    endTime: 22.05,
  },
  {
    id: "w7",
    employeeId: "emp2",
    dayKey: "mar",
    startTime: 14.0,
    endTime: 22.0,
  },
  {
    id: "w8",
    employeeId: "emp2",
    dayKey: "mié",
    startTime: 14.75,
    endTime: 22.0,
  },
  // No work for emp2 on Thursday (w9)
  {
    id: "w10",
    employeeId: "emp2",
    dayKey: "vie",
    startTime: 14.0,
    endTime: 23.5,
  },
  // Juan Pérez (emp3)
  {
    id: "w11",
    employeeId: "emp3",
    dayKey: "lun",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "w12",
    employeeId: "emp3",
    dayKey: "mar",
    startTime: 9.0,
    endTime: 18.0,
  },
  {
    id: "w13",
    employeeId: "emp3",
    dayKey: "sáb",
    startTime: 9.0,
    endTime: 13.0,
  },
  {
    id: "w15",
    employeeId: "emp3",
    dayKey: "mié",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "w16",
    employeeId: "emp3",
    dayKey: "jue",
    startTime: 10.0,
    endTime: 17.0,
  },
  {
    id: "w17",
    employeeId: "emp3",
    dayKey: "vie",
    startTime: 9.0,
    endTime: 16.5,
  },
  // Luis Gómez (emp4) - Mostly normal
  {
    id: "w18",
    employeeId: "emp4",
    dayKey: "lun",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "w19",
    employeeId: "emp4",
    dayKey: "mar",
    startTime: 8.9,
    endTime: 17.1,
  },
  {
    id: "w20",
    employeeId: "emp4",
    dayKey: "mié",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "w21",
    employeeId: "emp4",
    dayKey: "jue",
    startTime: 9.2,
    endTime: 17.0,
  }, // Late start
  {
    id: "w22",
    employeeId: "emp4",
    dayKey: "vie",
    startTime: 9.0,
    endTime: 16.8,
  }, // Left early
  // Sofía Martínez (emp5)
  {
    id: "w23",
    employeeId: "emp5",
    dayKey: "mar",
    startTime: 7.0,
    endTime: 15.0,
  },
  {
    id: "w24",
    employeeId: "emp5",
    dayKey: "mié",
    startTime: 6.9,
    endTime: 15.1,
  },
  // No work for emp5 on Thursday (w25) - Absence
  {
    id: "w26",
    employeeId: "emp5",
    dayKey: "vie",
    startTime: 7.0,
    endTime: 15.0,
  },
  {
    id: "w27",
    employeeId: "emp5",
    dayKey: "sáb",
    startTime: 8.0,
    endTime: 14.0,
  },
  // Ricardo Díaz (emp6) - Normal
  {
    id: "w28",
    employeeId: "emp6",
    dayKey: "lun",
    startTime: 8.0,
    endTime: 16.0,
  },
  {
    id: "w29",
    employeeId: "emp6",
    dayKey: "mar",
    startTime: 8.0,
    endTime: 16.0,
  },
  {
    id: "w30",
    employeeId: "emp6",
    dayKey: "mié",
    startTime: 8.0,
    endTime: 16.0,
  },
  {
    id: "w31",
    employeeId: "emp6",
    dayKey: "jue",
    startTime: 8.0,
    endTime: 16.0,
  },
  {
    id: "w32",
    employeeId: "emp6",
    dayKey: "vie",
    startTime: 8.0,
    endTime: 16.0,
  },
  // Elena Fernández (emp7)
  {
    id: "w33",
    employeeId: "emp7",
    dayKey: "lun",
    startTime: 10.0,
    endTime: 18.0,
  },
  {
    id: "w34",
    employeeId: "emp7",
    dayKey: "mar",
    startTime: 10.0,
    endTime: 19.0,
  }, // Overtime
  {
    id: "w35",
    employeeId: "emp7",
    dayKey: "mié",
    startTime: 10.1,
    endTime: 18.0,
  }, // Late start
  {
    id: "w36",
    employeeId: "emp7",
    dayKey: "jue",
    startTime: 10.0,
    endTime: 18.0,
  },
  {
    id: "w37",
    employeeId: "emp7",
    dayKey: "vie",
    startTime: 10.0,
    endTime: 18.0,
  },
  // Javier Morales (emp8) - Night shift simplified
  {
    id: "w38",
    employeeId: "emp8",
    dayKey: "lun",
    startTime: 22.0,
    endTime: 6.0,
  },
  {
    id: "w39",
    employeeId: "emp8",
    dayKey: "mar",
    startTime: 21.9,
    endTime: 6.1,
  },
  {
    id: "w40",
    employeeId: "emp8",
    dayKey: "mié",
    startTime: 22.0,
    endTime: 6.0,
  },
  {
    id: "w41",
    employeeId: "emp8",
    dayKey: "jue",
    startTime: 22.0,
    endTime: 6.0,
  },
  {
    id: "w42",
    employeeId: "emp8",
    dayKey: "vie",
    startTime: 22.0,
    endTime: 5.8,
  }, // Left early
  // Patricia Núñez (emp9)
  // No work for emp9 on Monday (w43) - Absence
  {
    id: "w44",
    employeeId: "emp9",
    dayKey: "mar",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "w45",
    employeeId: "emp9",
    dayKey: "mié",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "w46",
    employeeId: "emp9",
    dayKey: "jue",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "w47",
    employeeId: "emp9",
    dayKey: "vie",
    startTime: 9.0,
    endTime: 17.0,
  },
  // Andrés Castro (emp10) - Matches schedule, includes OT
  {
    id: "w48",
    employeeId: "emp10",
    dayKey: "lun",
    startTime: 8.0,
    endTime: 18.0,
  },
  {
    id: "w49",
    employeeId: "emp10",
    dayKey: "mar",
    startTime: 9.0,
    endTime: 17.0,
  },
  {
    id: "w50",
    employeeId: "emp10",
    dayKey: "mié",
    startTime: 9.0,
    endTime: 16.0,
  },
  {
    id: "w51",
    employeeId: "emp10",
    dayKey: "jue",
    startTime: 8.5,
    endTime: 17.5,
  },
  {
    id: "w52",
    employeeId: "emp10",
    dayKey: "vie",
    startTime: 10.0,
    endTime: 19.0,
  },
  {
    id: "w53",
    employeeId: "emp10",
    dayKey: "sáb",
    startTime: 9.0,
    endTime: 13.0,
  },
];

export const mockMarkings = [
  // (Data from previous response - kept for brevity)
  // Ana María Santos (emp1)
  {
    id: "m1",
    employeeId: "emp1",
    dayKey: "lun",
    time: 8.0,
    type: "ENTRADA",
    icon: MapPin,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m2",
    employeeId: "emp1",
    dayKey: "lun",
    time: 16.0,
    type: "SALIDA",
    icon: MapPin,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m3",
    employeeId: "emp1",
    dayKey: "mar",
    time: 7.9,
    type: "ENTRADA",
    icon: Clock,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m4",
    employeeId: "emp1",
    dayKey: "mar",
    time: 16.1,
    type: "SALIDA",
    icon: Clock,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m5",
    employeeId: "emp1",
    dayKey: "mié",
    time: 9.5,
    type: "ENTRADA",
    icon: Fingerprint,
    color:
      "text-orange-600 bg-white rounded-full p-0.5 border border-orange-600",
  }, // Late
  {
    id: "m6",
    employeeId: "emp1",
    dayKey: "mié",
    time: 16.0,
    type: "SALIDA",
    icon: Fingerprint,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m7",
    employeeId: "emp1",
    dayKey: "jue",
    time: 8.0,
    type: "ENTRADA",
    icon: MapPin,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m8",
    employeeId: "emp1",
    dayKey: "jue",
    time: 17.5,
    type: "SALIDA",
    icon: MapPin,
    color: "text-blue-700 bg-white rounded-full p-0.5 border border-blue-700",
  }, // OT Exit
  {
    id: "m9",
    employeeId: "emp1",
    dayKey: "vie",
    time: 8.0,
    type: "ENTRADA",
    icon: Clock,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m10",
    employeeId: "emp1",
    dayKey: "vie",
    time: 15.0,
    type: "SALIDA",
    icon: Clock,
    color:
      "text-orange-600 bg-white rounded-full p-0.5 border border-orange-600",
  }, // Early Exit
  {
    id: "m19",
    employeeId: "emp1",
    dayKey: "sáb",
    time: 9.1,
    type: "ENTRADA",
    icon: MapPin,
    color:
      "text-orange-600 bg-white rounded-full p-0.5 border border-orange-600",
  }, // Late Sat
  {
    id: "m20",
    employeeId: "emp1",
    dayKey: "sáb",
    time: 12.8,
    type: "SALIDA",
    icon: MapPin,
    color:
      "text-orange-600 bg-white rounded-full p-0.5 border border-orange-600",
  }, // Early Sat
  // Carmen Rodríguez (emp2)
  {
    id: "m11",
    employeeId: "emp2",
    dayKey: "mar",
    time: 14.0,
    type: "ENTRADA",
    icon: MapPin,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m12",
    employeeId: "emp2",
    dayKey: "mar",
    time: 22.0,
    type: "SALIDA",
    icon: MapPin,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m13",
    employeeId: "emp2",
    dayKey: "mié",
    time: 14.75,
    type: "ENTRADA",
    icon: Fingerprint,
    color:
      "text-orange-600 bg-white rounded-full p-0.5 border border-orange-600",
  }, // Late
  {
    id: "m14",
    employeeId: "emp2",
    dayKey: "mié",
    time: 22.0,
    type: "SALIDA",
    icon: Fingerprint,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m15",
    employeeId: "emp2",
    dayKey: "vie",
    time: 14.0,
    type: "ENTRADA",
    icon: Clock,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m16",
    employeeId: "emp2",
    dayKey: "vie",
    time: 23.5,
    type: "SALIDA",
    icon: Clock,
    color: "text-blue-700 bg-white rounded-full p-0.5 border border-blue-700",
  }, // OT Exit
  // Juan Pérez (emp3)
  {
    id: "m17",
    employeeId: "emp3",
    dayKey: "lun",
    time: 9.0,
    type: "ENTRADA",
    icon: MapPin,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m18",
    employeeId: "emp3",
    dayKey: "lun",
    time: 17.0,
    type: "SALIDA",
    icon: MapPin,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m21",
    employeeId: "emp3",
    dayKey: "mar",
    time: 9.0,
    type: "ENTRADA",
    icon: Clock,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m22",
    employeeId: "emp3",
    dayKey: "mar",
    time: 18.0,
    type: "SALIDA",
    icon: Clock,
    color: "text-blue-700 bg-white rounded-full p-0.5 border border-blue-700",
  }, // OT Exit
  {
    id: "m23",
    employeeId: "emp3",
    dayKey: "sáb",
    time: 9.0,
    type: "ENTRADA",
    icon: MapPin,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m24",
    employeeId: "emp3",
    dayKey: "sáb",
    time: 13.0,
    type: "SALIDA",
    icon: MapPin,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m25",
    employeeId: "emp3",
    dayKey: "mié",
    time: 9.0,
    type: "ENTRADA",
    icon: Fingerprint,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m26",
    employeeId: "emp3",
    dayKey: "mié",
    time: 17.0,
    type: "SALIDA",
    icon: Fingerprint,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m27",
    employeeId: "emp3",
    dayKey: "jue",
    time: 10.0,
    type: "ENTRADA",
    icon: Clock,
    color:
      "text-orange-600 bg-white rounded-full p-0.5 border border-orange-600",
  }, // Late
  {
    id: "m28",
    employeeId: "emp3",
    dayKey: "jue",
    time: 17.0,
    type: "SALIDA",
    icon: Clock,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m29",
    employeeId: "emp3",
    dayKey: "vie",
    time: 9.0,
    type: "ENTRADA",
    icon: MapPin,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m30",
    employeeId: "emp3",
    dayKey: "vie",
    time: 16.5,
    type: "SALIDA",
    icon: MapPin,
    color:
      "text-orange-600 bg-white rounded-full p-0.5 border border-orange-600",
  }, // Early Exit

  // Markings for emp4 - emp10 (Simplified examples)
  // Luis Gómez (emp4)
  {
    id: "m31",
    employeeId: "emp4",
    dayKey: "lun",
    time: 9.0,
    type: "ENTRADA",
    icon: MapPin,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m32",
    employeeId: "emp4",
    dayKey: "lun",
    time: 17.0,
    type: "SALIDA",
    icon: MapPin,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m33",
    employeeId: "emp4",
    dayKey: "mar",
    time: 8.9,
    type: "ENTRADA",
    icon: Clock,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m34",
    employeeId: "emp4",
    dayKey: "mar",
    time: 17.1,
    type: "SALIDA",
    icon: Clock,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m35",
    employeeId: "emp4",
    dayKey: "jue",
    time: 9.2,
    type: "ENTRADA",
    icon: Fingerprint,
    color:
      "text-orange-600 bg-white rounded-full p-0.5 border border-orange-600",
  }, // Late
  {
    id: "m36",
    employeeId: "emp4",
    dayKey: "jue",
    time: 17.0,
    type: "SALIDA",
    icon: Fingerprint,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m37",
    employeeId: "emp4",
    dayKey: "vie",
    time: 9.0,
    type: "ENTRADA",
    icon: MapPin,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m38",
    employeeId: "emp4",
    dayKey: "vie",
    time: 16.8,
    type: "SALIDA",
    icon: MapPin,
    color:
      "text-orange-600 bg-white rounded-full p-0.5 border border-orange-600",
  }, // Early Exit

  // Sofía Martínez (emp5)
  {
    id: "m39",
    employeeId: "emp5",
    dayKey: "mar",
    time: 7.0,
    type: "ENTRADA",
    icon: MapPin,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m40",
    employeeId: "emp5",
    dayKey: "mar",
    time: 15.0,
    type: "SALIDA",
    icon: MapPin,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m41",
    employeeId: "emp5",
    dayKey: "vie",
    time: 7.0,
    type: "ENTRADA",
    icon: Clock,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m42",
    employeeId: "emp5",
    dayKey: "vie",
    time: 15.0,
    type: "SALIDA",
    icon: Clock,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m43",
    employeeId: "emp5",
    dayKey: "sáb",
    time: 8.0,
    type: "ENTRADA",
    icon: MapPin,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m44",
    employeeId: "emp5",
    dayKey: "sáb",
    time: 14.0,
    type: "SALIDA",
    icon: MapPin,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },

  // Elena Fernández (emp7)
  {
    id: "m45",
    employeeId: "emp7",
    dayKey: "lun",
    time: 10.0,
    type: "ENTRADA",
    icon: MapPin,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m46",
    employeeId: "emp7",
    dayKey: "lun",
    time: 18.0,
    type: "SALIDA",
    icon: MapPin,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m47",
    employeeId: "emp7",
    dayKey: "mar",
    time: 10.0,
    type: "ENTRADA",
    icon: Clock,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m48",
    employeeId: "emp7",
    dayKey: "mar",
    time: 19.0,
    type: "SALIDA",
    icon: Clock,
    color: "text-blue-700 bg-white rounded-full p-0.5 border border-blue-700",
  }, // OT Exit

  // Andrés Castro (emp10)
  {
    id: "m49",
    employeeId: "emp10",
    dayKey: "lun",
    time: 8.0,
    type: "ENTRADA",
    icon: MapPin,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m50",
    employeeId: "emp10",
    dayKey: "lun",
    time: 18.0,
    type: "SALIDA",
    icon: MapPin,
    color: "text-blue-700 bg-white rounded-full p-0.5 border border-blue-700",
  }, // OT Exit
  {
    id: "m51",
    employeeId: "emp10",
    dayKey: "mar",
    time: 9.0,
    type: "ENTRADA",
    icon: Clock,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m52",
    employeeId: "emp10",
    dayKey: "mar",
    time: 17.0,
    type: "SALIDA",
    icon: Clock,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  {
    id: "m53",
    employeeId: "emp10",
    dayKey: "sáb",
    time: 9.0,
    type: "ENTRADA",
    icon: MapPin,
    color: "text-green-700 bg-white rounded-full p-0.5 border border-green-700",
  },
  {
    id: "m54",
    employeeId: "emp10",
    dayKey: "sáb",
    time: 13.0,
    type: "SALIDA",
    icon: MapPin,
    color: "text-red-700 bg-white rounded-full p-0.5 border border-red-700",
  },
  // ... Add more markings as needed for emp6, emp8, emp9, and variations
];
